[package]
name = "odata"
version = "0.1.0"
authors = ["Matt George <matt@mattgeorge.net>"]

[dependencies]
serde_json = "1.0"
serde_derive = "1.0.4"
serde = "1.0.4"
hyper = "0.10"
time = "0.1.37"
lazy_static = "0.2"
