[package]
name = "rust_odata"
version = "0.1.0"
authors = ["Matt George <matt@mattgeorge.net>"]

[dependencies]
lazy_static = "0.2"
serde_json = "1.0"
serde_derive = "1.0.4"
serde = "1.0.4"
chrono = "0.3.1"